[WIP] [Add] Databaseクラスの作成
Huyu2239/GChub pull request #16
Opened 2020-09-26 15:23 UTC by daima3629

データベース処理用のクラスを作っています。
まだWIPですが、レビューは順次お待ちしています。

2020-09-26 15:25 UTC, daima3629 commented
あとついでに.gitignoreにCPythonのキャッシュバイナリファイルを追加しておきました

2020-09-27 03:50 UTC, daima3629 commented
あっやべlinterかけるの忘れてた()
あざす

2020-09-27 03:55 UTC, daima3629 commented
あの...まだWIPなんで、あんまり変なとこのコード修正はしないでもらいたいんですが...

2020-09-27 03:57 UTC, sevenc-nanashi commented
了解です（まあflake8の修正しかやってないんだけどね）

2020-09-27 06:03 UTC, daima3629 commented
typingのimportからTuple消したじゃないですか...
一応使うつもりなんですけど

2020-09-27 06:30 UTC, sevenc-nanashi commented
ごめんなさい（flake8がうるさい）

2020-09-29 22:01 UTC, Huyu2239 submitted a review, later dismissed
databaseのユーザー名をhuyuにして貰えますか？

2020-09-30 06:42 UTC, daima3629 commented
> databaseのユーザー名をhuyuにして貰えますか？

User名は.envにて指定する仕様になっています

2020-09-30 06:48 UTC, Huyu2239 commented
わかりました

2020-10-08 16:48 UTC, daima3629 commented
完成したので仕様を報告します。

---

class `Database` (on lib/database.py)

データベース操作を簡略化するためのクラスです。

methods(public):
- `__init__`
  argment(s):
  - `bot`
    `commands.Bot`インスタンスを指定してください。

- `close`
  no argments taken.
  
  コネクションを閉じる際に使用してください。
  Botを終了させるときなどに使用すべきです。

- `get_gchat`
  argment(s):
    - `gchat_id`
      取得したい`Gchat`オブジェクトのIDです。

  与えられたIDに対応する`Gchat`オブジェクトを返します。
  一致するものがなかった場合`None`を返します。

- `get_gchat_channels`
  argment(s):
  - `gchat_id`
    取得したい`GchatChannel`オブジェクトのリストに対応するGchat-IDです。

  与えられたGchat-IDに対応する`GchatChannel`オブジェクトのリストを返します。
  一致するものがなかった場合`None`を返します。

- `get_gchat_channel`
  argment(s):
  - `channel_id`
    取得したい`GchatChannel`オブジェクトに対応するチャンネルIDです。

  与えられたチャンネルIDに対応する`GchatChannel`オブジェクトを返します。
  このメソッドはチャンネルIDのみから`GchatChannel`オブジェクトを取得したいとき使用してください。
  一致するものがなかった場合`None`を返します。

- `create_gchat`
  argument(s):
  - `gchat_id`
    作成するGchatのIDです。
  - `owner_id`
    作成するGchatのオーナーのユーザーIDです。
  - `password`
    作成するGchatのパスワードです。

  新しくGchatを作成し、データベースに追加します。
  作成した`Gchat`オブジェクトを返します。

- `add_gchat_channel`
  argument(s):
  - `channel_id`
    追加するチャンネルのIDです。
  - `gchat_id`
    追加されるGchatのIDです。

  Gchatに新たなチャンネルを追加します。
  `gchat_id`に対応するGchatが見つからなかった場合、`ValueError`をraiseします。
  追加されたら、その`GchatChannel`オブジェクトを返します。

- `delete_gchat`
  argument(s):
  - `gchat_id`
    削除するGchatのIDです。

  Gchatをデータベースから削除します。
  存在しないGchatのIDを指定した場合、`ValueError`をraiseします。

- `delete_gchat_channel`
  argument(s):
  - `channel_id`
    削除するチャンネルのIDです。
  - `gchat_id`
    チャンネルが削除されるGchatのIDです。

  指定されたGchatから指定されたチャンネルを削除します。
  存在しないGchatID、もしくはチャンネルIDを指定した場合、`ValueError`をraiseします。


That's all.

2020-10-08 18:48 UTC, Shirataki2 requested changes
手元の環境で一通り検証を行いました．

2020-10-08 18:48 UTC, Shirataki2 commented on lib/database.py
> +            ''')
2回目以降起動時にDuplicateTableErrorが発生しました．

私の環境だけかもなので検証をお願いします

```py
Traceback (most recent call last):
  File "/home/ishii/.local/share/virtualenvs/bot-LeqKob9R/lib/python3.8/site-packages/jishaku/cog_base.py", line 508, in jsk_python
    async for send, result in AsyncSender(executor):
  File "/home/ishii/.local/share/virtualenvs/bot-LeqKob9R/lib/python3.8/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "/home/ishii/.local/share/virtualenvs/bot-LeqKob9R/lib/python3.8/site-packages/jishaku/repl/compilation.py", line 137, in traverse
    async for send, result in AsyncSender(func(*self.args)):
  File "/home/ishii/.local/share/virtualenvs/bot-LeqKob9R/lib/python3.8/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "<repl>", line 1, in _repl_coroutine
  File "/home/ishii/projects/GChub/lib/database.py", line 71, in get_gchat_channels
    conn = self.conn or await self._setup_connection()
  File "/home/ishii/projects/GChub/lib/database.py", line 61, in _setup_connection
    await self._check_database(self.conn)
  File "/home/ishii/projects/GChub/lib/database.py", line 32, in _check_database
    await self.conn.execute('''
asyncpg.exceptions.DuplicateTableError: relation "gchat" already exists
```

2020-10-08 18:48 UTC, Shirataki2 commented on lib/database.py
> +                    FOREIGN KEY(gchat_id) REFERENCES global_chat(gchat_id)
リファレンス先がないと怒られました

`FOREIGN KEY(gchat_id) REFERENCES gchat(gchat_id)`

2020-10-08 18:48 UTC, Shirataki2 commented on lib/database.py
> +        """setup connection and returns `asycnpg.Connection` object."""
コメントですがtypoです`asycnpg`->`asyncpg`

2020-10-08 18:48 UTC, Shirataki2 commented on lib/database.py
> +        await self.check_database()
`await self._check_database(self.conn)`

2020-10-08 18:48 UTC, Shirataki2 commented on lib/database.py
> +        conn = self.conn or await self.setup_connection()
以降の関数もprivateに変更お願いします．
`conn = self.conn or await self._setup_connection()`

2020-10-08 18:48 UTC, Shirataki2 commented on lib/database.py
> +        channel_records = await conn.fetch(f'SELECT * FROM ghat_chnnels WHERE gchat_id="{gchat_id}"')
typo
`channel_records = await conn.fetch(f'SELECT * FROM ghat_chnnels WHERE gchat_id="{gchat_id}"')`
↓
`channel_records = await conn.fetch(f'SELECT * FROM gchat_channels WHERE gchat_id="{gchat_id}"')`

2020-10-08 22:44 UTC, daima3629 commented
わお...flake8のlintだけじゃ少し足りなかったみたいですね、たくさんのご指摘ありがとうございます！
帰ったら修正します。
それから、`DupliateTableError`が発生する問題についてはこちらでは環境が整わず検証のしようがないので、どなたか追加検証をお願いします...

2020-10-08 23:49 UTC, Shirataki2 commented
自分の手元で検証できそうなので修正ブランチでしておきます！

2020-10-09 15:57 UTC, Shirataki2 approved these changes

2020-10-10 14:09 UTC, disneyresidents approved these changes
LGTM.
good job!

2020-10-10 14:44 UTC, Huyu2239 approved these changes

2020-10-10 14:55 UTC, daima3629 commented
あれ、check failedしてるのにMergeボタン押せるな()
じゃあMergeします、ありがとうございました！

2020-10-10 14:55 UTC, merged